# Spring configuration
spring:
  application:
    name: api-publish-service

# Dubbo configuration
dubbo:
  registry:
    empty-protection: true
  application:
    name: ${spring.application.name}
    # Enable QoS for management
    qos-enable: true
    qos-accept-foreign-ip: true
  registries:
    nacos-internal:
      address: nacos://host.docker.internal:30848
      group: INTERNAL-GROUP
    nacos-public:
      address: nacos://host.docker.internal:30848
      # group 名称不要包含下划线，否则由于 DNS-1123 标签标准要求，在 higress 中会自动转换为短横线连接
      group: PUBLIC-GROUP
  protocols:
    tri:
      name: tri
      port: 50053
      serialization: fastjson2
      registry-ids: nacos-public
    dubbo:
      name: dubbo
      port: 50054
      serialization: fury
      registry-ids: nacos-internal
  metadata-report:
    address: nacos://host.docker.internal:30848

# Logging configuration
logging:
  level:
    root: INFO
    org.apache.dubbo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
